# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pic/'),
        ),
    ]
