# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_animal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='habitat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
