# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pending',
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Pending'), (None, 'Published')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='class_name',
            field=models.CharField(choices=[(None, 'Mammal'), (None, 'Reptile'), (None, 'Amphibian'), (None, 'Fish'), (None, 'Bird')], max_length=10),
        ),
    ]
