# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_auto_20170503_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='class_name',
            field=models.CharField(choices=[('Mammal', 'Mammal'), ('Reptile', 'Reptile'), ('Amphibian', 'Amphibian'), ('Fish', 'Fish'), ('Bird', 'Bird')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Published', 'Published')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='park.Animal'),
        ),
    ]
